services:
  app:
    build:
      context: .
    image: laravel-react-app
    container_name: laravel-react-app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
      - "5173:5173"  # Laravel will run on 8000
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ssmultiversecrm_crm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"    

volumes:
  dbdata: